# Generated by Django 3.2.23 on 2024-02-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('malumot', models.TextField()),
                ('rasm', models.ImageField(upload_to='media')),
                ('sana', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('lavozimi', models.CharField(max_length=50)),
                ('malumot', models.TextField()),
                ('insta', models.CharField(max_length=30)),
                ('tg', models.CharField(max_length=30)),
                ('twit', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=30)),
                ('rasm', models.ImageField(upload_to='media')),
                ('sana', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('rasm', models.ImageField(upload_to='media')),
                ('sana', models.DateField(auto_now=True)),
                ('web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfolder.web')),
            ],
        ),
    ]
